Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.0.10"


  config.vm.synced_folder "/data/www","/data/www",create:true
  config.ssh.username = "root"
  #config.ssh.password = "vagrant"
  #config.ssh.insert_key = "true"
  config.ssh.private_key_path = "/Users/cwd/.ssh/id_rsa"
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
